#!/usr/bin/env python
# encoding: utf-8
#
# Copyright 2011 Greg Neagle.
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
getIncompatibleAppListPkg

Created by Greg Neagle on 2011-09-07.
"""

import subprocess
import sys
import os
import plistlib

from xml.parsers.expat import ExpatError

PKGNAME = 'MacOS_10_7_IncompatibleAppList.pkg'
LION_CATALOG_URL = ('http://swscan.apple.com/content/catalogs/others/'
                    'index-lion-snowleopard-leopard.merged-1.sucatalog')


def downloadURL(URL, to_file=None):
    '''Downloads URL to the current directory or as string'''
    cmd = ['/usr/bin/curl', '--silent', '--show-error', '--url', URL]
    if to_file:
        cmd.extend(['-o', to_file])
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, err) = proc.communicate()
    if proc.returncode:
        print >> sys.stderr, 'Error %s retrieving %s' % (proc.returncode, URL)
        print >> sys.stderr, err
    if not to_file:
        return output


def findIncompatibleAppListPkgURL():
    '''Searches Lion SU catalog to find a download URL for 
    MacOS_10_7_IncompatibleAppList.pkg. If there's more than one, returns the 
    one with the most recent PostDate.'''
    
    def sort_by_PostDate(a, b):
        """Internal comparison function for use with sorting"""
        return cmp(b['PostDate'], a['PostDate'])
    catalog_str = downloadURL(LION_CATALOG_URL)
    try:
        catalog = plistlib.readPlistFromString(catalog_str)
    except ExpatError:
        print >> sys.stderr, 'Could not parse catalog!'
        return None
    product_list = []
    if 'Products' in catalog:
        for product_key in catalog['Products'].keys():
            product = catalog['Products'][product_key]
            for package in product.get('Packages', []):
                url = package.get('URL','')
                if url.endswith(PKGNAME):
                    product_list.append({'PostDate': product['PostDate'],
                                         'URL': url})
        if product_list:
            product_list.sort(sort_by_PostDate)
            return product_list[0]['URL']
    return None


def main():
    '''Retrieves Lion SU catalog, looks for download URL for 
    MacOS_10_7_IncompatibleAppList.pkg, downloads that and makes an
    index.sproduct file in the current directory.'''
    url = findIncompatibleAppListPkgURL()
    if url:
        print 'Downloading %s...' % url
        downloadURL(url, to_file=PKGNAME)
        if os.path.exists(PKGNAME):
            # make index.sproduct
            pkg_info = {}
            pkg_info['Identifier'] = 'com.apple.pkg.CompatibilityUpdate'
            pkg_info['Size'] = int(os.path.getsize(PKGNAME))
            pkg_info['URL'] = PKGNAME
            pkg_info['Version'] = '10.7'
            index_dict = {}
            index_dict['Packages'] = [pkg_info]
            print "Writing index.sproduct..."
            plistlib.writePlist(index_dict, 'index.sproduct')
            print "Done."


if __name__ == '__main__':
    main()

